spring:
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=USER
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
  h2:
    console.enabled: true
server:
  port: 6161