spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/vibbrademo
    username: services
    password: 123123
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  h2:
    console.enabled: true
server:
  port: 6161
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

